# version: "3.9"

services:
  frontend:
    # image: wiings09/frontend-rating-app:v1
    image: wiings09/k8s-rating-app:local
    container_name: frontend
    ports:
      - "8080:80"    # frontend exposed on host
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000/api   # ðŸ‘ˆ use service name, not localhost

  backend:
    image: wiings09/backend-rating-app:v1
    container_name: backend
    ports:
      - "5000:5000"   # backend exposed on host
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"   # only needed if you want to connect via Compass
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
