name: CI/CD Pipeline for Rating App
on:
  push:
    branches:
      - cicd

env: 
  APP_NAME: rating-app
  NAMESPACE: project4

jobs:
  build:
    name: Docker Build Images
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.NEW_TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Generate New Tag
        id: tag
        run: |
          TAG=$(curl -s https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/rating-frontend/tags/?page_size=1 | jq -r '.results[0].name' || echo "cicdV0")
          NUM=$(echo $TAG | sed 's/[^0-9]*//g')
          NEXT=$((NUM + 1))
          NEW_TAG="cicdV$NEXT"
          echo "NEW_TAG=$NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Build Docker Images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/rating-frontend:${{ steps.tag.outputs.NEW_TAG }} --build-arg VITE_API_URL=http://myapp.local/api ./frontend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/rating-backend:${{ steps.tag.outputs.NEW_TAG }} ./backend


  push:
    name: Push Docker Images
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull and Push Images
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/rating-frontend:${{ needs.build.outputs.tag }}
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/rating-backend:${{ needs.build.outputs.tag }}

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rating-frontend:${{ needs.build.outputs.tag }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rating-backend:${{ needs.build.outputs.tag }}

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up kubectl and helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml
          kubectl config use-context ${{ secrets.KUBE_CONTEXT }}

      - name: Helm Deploy
        run: |
          helm upgrade --install $APP_NAME ./rating-app \
            --namespace $NAMESPACE \
            --create-namespace \
            --set frontend.image=${{ secrets.DOCKERHUB_USERNAME }}/rating-frontend:${{ needs.build.outputs.tag }} \
            --set backend.image=${{ secrets.DOCKERHUB_USERNAME }}/rating-backend:${{ needs.build.outputs.tag }}
