name: CI/CD Pipeline for Rating App
on:
  push:
    branches:
      - cicd

env: 
  APP_NAME: rating-app
  NAMESPACE: project4

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.NEW_TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Generate New Tag
        id: tag
        run: |
          TAG=$(curl -s https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/k8s-rating-frontend/tags/?page_size=1 | jq -r '.results[0].name' || echo "cicdV0")
          NUM=$(echo $TAG | sed 's/[^0-9]*//g')
          NEXT=$((NUM + 1))
          NEW_TAG="cicdV$NEXT"
          echo "NEW_TAG=$NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/k8s-rating-frontend:${{ steps.tag.outputs.NEW_TAG }} --build-arg VITE_API_URL=http://myapp.local/api ./frontend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend-rating-app:${{ steps.tag.outputs.NEW_TAG }} ./backend

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/k8s-rating-frontend:${{ steps.tag.outputs.NEW_TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend-rating-app:${{ steps.tag.outputs.NEW_TAG }}

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push
    env:
      APP_NAME: rating-app
      NAMESPACE: project3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up kubectl and helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          echo "KUBECONFIG=$(pwd)/kubeconfig.yaml" >> $GITHUB_ENV
          kubectl config get-contexts
          kubectl config use-context ${{ secrets.KUBE_CONTEXT }}

      - name: Verify Kubernetes Access
        run: kubectl get nodes

      - name: Helm Deploy
        run: |
          helm upgrade --install $APP_NAME ./rating-app \
            --namespace $NAMESPACE \
            --create-namespace \
            --set frontend.image=${{ secrets.DOCKERHUB_USERNAME }}/k8s-rating-frontend:${{ needs.build-and-push.outputs.tag }} \
            --set backend.image=${{ secrets.DOCKERHUB_USERNAME }}/backend-rating-app:${{ needs.build-and-push.outputs.tag }}
